import {
  Button,
  Toast,
  Tabbar,
  TabbarItem,
  Cell,
  CellGroup,
  Icon,
  Navbar,
  Tabs,
  TabPane,
  Avatar,
  Input,
  Form,
  FormItem,
  Swiper,
  SwiperItem,
  Divider,
  Popup,
  OverLay,
  TextArea,
  Category,
  CategoryPane,
  Card,
  Tag,
  Price,
  InputNumber,
  List,
  Dialog,
  ImagePreview,
  BackTop,
  Sku,
  Address,
  Elevator,
  Empty,
  Checkbox,
  CheckboxGroup,
  ActionSheet,
  Grid,
  GridItem,
  AddressList,
  Switch,
  DatePicker,
  Picker,
  Radio,
  RadioGroup,
} from "@nutui/nutui-taro";

export default {
  install(app) {
    // 此处形参为main.js文件中use()方法自动传进来的Vue实例
    app
      .use(Button)
      .use(Navbar)
      .use(Icon)
      .use(Toast)
      .use(Tabbar)
      .use(TabbarItem)
      .use(Cell)
      .use(CellGroup)
      .use(Tabs)
      .use(TabPane)
      .use(Avatar)
      .use(Form)
      .use(FormItem)
      .use(Input)
      .use(Swiper)
      .use(SwiperItem)
      .use(Divider)
      .use(Popup)
      .use(OverLay)
      .use(TextArea)
      .use(Category)
      .use(CategoryPane)
      .use(Card)
      .use(Tag)
      .use(Price)
      .use(InputNumber)
      .use(List)
      .use(Dialog)
      .use(ImagePreview)
      .use(BackTop)
      .use(Sku)
      .use(Address)
      .use(Elevator)
      .use(Empty)
      .use(Checkbox)
      .use(CheckboxGroup)
      .use(ActionSheet)
      .use(Grid)
      .use(GridItem)
      .use(AddressList)
      .use(Switch)
      .use(DatePicker)
      .use(Picker)
      .use(Radio)
      .use(RadioGroup);
  },
};
